In [16]:
import numpy as np 
import pandas as pd 
from sklearn import preprocessing, neighbors, svm
from sklearn.model_selection import train_test_split

df = pd.read_csv('collect_color_data.csv')

In [17]:
df.head()

labels  color_1  color_2  color_3
0       1      244       33      106
1       1       43       78      102
2       0      159      179      135
3       0      238      145       77
4       1      214       40      166

In [18]:
df = df.dropna()

In [19]:
X = np.array(df.drop(['labels'], 1))

In [20]:
y = np.array(df['labels'])

In [21]:
scaler = preprocessing.scale(X)
X = scaler
print(X)

[[ 1.62589687 -1.25761762 -0.33121134]
 [-1.17684892 -0.64158305 -0.38545153]
 [ 0.44065611  0.74107232  0.06203   ]
 [ 1.54223282  0.27562398 -0.72445268]
 [ 1.2075766  -1.16179002  0.48239143]
 [-0.87008073 -1.33975556  0.07559005]
 [ 0.77531233  1.31603792 -0.43969171]
 [-1.65094523  0.82321026  1.54007504]
 [ 1.63984088  1.41186552  0.26543069]
 [ 0.84503237  1.60352072  0.99767319]
 [ 1.68167291  0.72738266  0.06203   ]
 [ 1.50040079  0.78214129 -1.64653583]
 [-0.71669663 -0.95644516 -0.77869287]
 [-0.64697658 -1.59985905  0.36035102]
 [ 1.13785656  1.56245175  0.4145912 ]
 [-0.85613672  0.86427923 -0.57529217]
 [ 0.14783192 -1.53141076 -1.7550162 ]
 [ 1.58406484  0.54941712 -1.13125407]
 [-0.36809641  1.65827934 -1.21261435]
 [ 0.8868644  -0.86061756  0.21119051]
 [-1.17684892  1.192831    1.62143532]
 [ 0.45460012  0.15241706 -1.67365592]
 [ 1.47251277  0.56310678  1.60787527]
 [-1.46967311  1.35710689  0.65867203]
 [ 0.13388792  0.63155506  0.38747111]
 [-0.42387244  0.8095206 

C:\Users\user\Miniconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [22]:
X.shape

(329, 3)

In [23]:
y.shape

(329,)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [25]:
from sklearn.externals import joblib
clf = joblib.load('color_classifier_svm.pkl')

In [26]:
# clf.fit(X_train, y_train)

In [29]:
svm_X = np.array([X_test[0]]).reshape(-1,1)
svm_X = np.array(svm_X).reshape(1,-1)
svm_y = np.array([y_test[0]]).reshape(-1,1)
svm_y = np.array(svm_y).reshape(1,-1)
# accuracy = clf.score(svm_X, svm_y)
print(clf.predict(svm_X))

[1]


In [28]:
# from sklearn.externals import joblib
# joblib.dump(clf, 'color_classifier_svm.pkl')